name: Build and Deploy Bookdown

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("bookdown", "rmarkdown", "knitr"))'

      - name: Render book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

      - name: Check for index.html
        run: |
          echo "Listing files in docs/"
          ls -l docs/
          if [ ! -f "docs/index.html" ]; then
            echo "::error::index.html was not created!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
